a = input('digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaçoes ?', a.isspace())
print('É um numero ?', a.isnumeric())
print('É alfabetico ?', a.isalpha())
print('É alfa numerico ?', a.isalnum())
print('Está em maiusculas ?', a.isupper())
print('Está em minusculas ?', a.islower())
print('Está capitalizada ?', a.istitle())